name: Deploy to GCP VM

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'automation-services-380919'
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to VM
      run: |
        gcloud compute ssh ${{ secrets.GCP_INSTANCE_NAME }} --zone=${{ secrets.GCP_ZONE }} --command="
          sudo -u vicente_g bash -c "cd /home/app/sample-gcp-deployment && git pull origin main"
        "
