name: Deploy to GCP VM

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'automation-services-380919'
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
